// pasko_28.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <string>
using namespace std;

int main()
{
    string fileName;
    cout << "Enter the file name:";
    cin >> fileName;

    try 
    {
        // Some code to open the file...

        // Error while opening the file (this error will generated not by you.
        // It will be generated by system functions.
        throw runtime_error("Could not open file");
    }
    catch (exception& ex)
    {
        cout << "Error message: " << ex.what() << endl;
    }
}
